// Fetch lessons on Homepage - Frontend
export const FETCH_LESSON = 'FETCH_LESSON';
export const FETCH_LESSON_SUCCESS = 'FETCH_LESSON_SUCCESS';
export const FETCH_LESSON_FAILED = 'FETCH_LESSON_FAILED';

// Fetch lesson detail - Frontend
export const FETCH_LESSON_DETAIL = 'FETCH_LESSON_DETAIL';
export const FETCH_LESSON_DETAIL_SUCCESS = 'FETCH_LESSON_DETAIL_SUCCESS';
export const FETCH_LESSON_DETAIL_FAILED = 'FETCH_LESSON_DETAIL_FAILED';



// Fetch phrase on Homepage - Frontend
export const FETCH_PHRASE = 'FETCH_PHRASE';
export const FETCH_PHRASE_SUCCESS = 'FETCH_PHRASE_SUCCESS';
export const FETCH_PHRASE_FAILED = 'FETCH_PHRASE_FAILED';

// Fetch phrase out Storage - Frontend
export const FETCH_PHRASE_OUT_STORAGE = 'FETCH_PHRASE_OUT_STORAGE';
export const FETCH_PHRASE_OUT_STORAGE_SUCCESS = 'FETCH_PHRASE_OUT_STORAGE_SUCCESS';
export const FETCH_PHRASE_OUT_STORAGE_FAILED = 'FETCH_PHRASE_OUT_STORAGE_FAILED';

// add phrase to Storage - Frontend
export const ADD_PHRASE_TO_STORAGE = 'ADD_PHRASE_TO_STORAGE';
export const ADD_PHRASE_TO_STORAGE_SUCCESS = 'ADD_PHRASE_TO_STORAGE_SUCCESS';
export const ADD_PHRASE_TO_STORAGE_FAILED = 'ADD_PHRASE_TO_STORAGE_FAILED';

// Fetch phrase in Storage - Frontend
export const FETCH_PHRASE_IN_STORAGE = 'FETCH_PHRASE_IN_STORAGE';
export const FETCH_PHRASE_IN_STORAGE_SUCCESS = 'FETCH_PHRASE_IN_STORAGE_SUCCESS';
export const FETCH_PHRASE_IN_STORAGE_FAILED = 'FETCH_PHRASE_IN_STORAGE_FAILED';

// remove phrase from Storage - Frontend
export const REMOVE_PHRASE_FROM_STORAGE = 'REMOVE_PHRASE_FROM_STORAGE';
export const REMOVE_PHRASE_FROM_STORAGE_SUCCESS = 'REMOVE_PHRASE_FROM_STORAGE_SUCCESS';
export const REMOVE_PHRASE_FROM_STORAGE_FAILED = 'REMOVE_PHRASE_FROM_STORAGE_FAILED';

// fetch phrase to learn - Frontend
export const FETCH_PHRASE_TO_LEARN = 'FETCH_PHRASE_TO_LEARN';
export const FETCH_PHRASE_TO_LEARN_SUCCESS = 'FETCH_PHRASE_TO_LEARN_SUCCESS';
export const FETCH_PHRASE_TO_LEARN_FAILED = 'FETCH_PHRASE_TO_LEARN_FAILED';



// Fetch word on Homepage - Frontend
export const FETCH_WORD = 'FETCH_WORD';
export const FETCH_WORD_SUCCESS = 'FETCH_WORD_SUCCESS';
export const FETCH_WORD_FAILED = 'FETCH_WORD_FAILED';

// Fetch word out Storage - Frontend
export const FETCH_WORD_OUT_STORAGE = 'FETCH_WORD_OUT_STORAGE';
export const FETCH_WORD_OUT_STORAGE_SUCCESS = 'FETCH_WORD_OUT_STORAGE_SUCCESS';
export const FETCH_WORD_OUT_STORAGE_FAILED = 'FETCH_WORD_OUT_STORAGE_FAILED';

// add word to Storage - Frontend
export const ADD_WORD_TO_STORAGE = 'ADD_WORD_TO_STORAGE';
export const ADD_WORD_TO_STORAGE_SUCCESS = 'ADD_WORD_TO_STORAGE_SUCCESS';
export const ADD_WORD_TO_STORAGE_FAILED = 'ADD_WORD_TO_STORAGE_FAILED';

// Fetch word in Storage - Frontend
export const FETCH_WORD_IN_STORAGE = 'FETCH_WORD_IN_STORAGE';
export const FETCH_WORD_IN_STORAGE_SUCCESS = 'FETCH_WORD_IN_STORAGE_SUCCESS';
export const FETCH_WORD_IN_STORAGE_FAILED = 'FETCH_WORD_IN_STORAGE_FAILED';

// remove word from Storage - Frontend
export const REMOVE_WORD_FROM_STORAGE = 'REMOVE_WORD_FROM_STORAGE';
export const REMOVE_WORD_FROM_STORAGE_SUCCESS = 'REMOVE_WORD_FROM_STORAGE_SUCCESS';
export const REMOVE_WORD_FROM_STORAGE_FAILED = 'REMOVE_WORD_FROM_STORAGE_FAILED';

// fetch word to learn - Frontend
export const FETCH_WORD_TO_LEARN = 'FETCH_WORD_TO_LEARN';
export const FETCH_WORD_TO_LEARN_SUCCESS = 'FETCH_WORD_TO_LEARN_SUCCESS';
export const FETCH_WORD_TO_LEARN_FAILED = 'FETCH_WORD_TO_LEARN_FAILED';



// Register new user - Frontend
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

// Login
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// Logout
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// Get User Info
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED';

// Update Profile
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';